### ISSUE TITLE
Not getting default values if output type is JSON

### ISSUE THREAD

**Issue by bahrus** [runem/web-component-analyzer#102]
This is a really impressive utility.

I've noticed that if I use the default formatter, I get a column for default values for properties.

But the default value is not provided if outputting to JSON.  Would be great if JSON could also support default values.

Also, if the default value is a JS object, the keys get truncated to the first letter, e.g.:

    newDataPointTestValue2 = {
        label: "test",
        index: 10,
        valueFromEachDataset: []
    };

produces {"l":"test","i":10,"v":[]}

**Comment by runem** [comment]
The `default` value is now included in the json output, and the issue with parsing default object literal has been fixed as well :tada:
