### ISSUE TITLE
[request] support @protected properties

### ISSUE THREAD

**Issue by bennypowers** [runem/web-component-analyzer#105]
This input

```js
import { LitElement, html, query } from 'lit-element';

/** @element */
class LeakyDocs extends LitElement {

  /**
   * Value
   * @attr
   */
  @property({ type: String }) value;
  
  /**
   * Internal input
   * @protected
   */
  @query('#input') input

  render() {
    return html`<input id="input" .value="${this.value}"/>`;
  }
}
```

produces this **current** output:

```md

## Properties

| Property | Attribute | Type    | Default | Description    |
|----------|-----------|---------|---------|----------------|
| `input`  |           | `any`   |         | Internal input |
| `value`  | `value`   | `string`|         | value          |
```

WCA should produce instead an **expected** output without the protected property

```md

## Properties

| Property | Attribute | Type    | Default | Description    |
|----------|-----------|---------|---------|----------------|
| `value`  | `value`   | `string`|         | value          |
```

**Comment by daKmoR** [comment]
imho protected properties can still be interesting for people extending your components...

only `@private` properties should be fully excluded.

I would like to see a `protected: true` in the `custom-elements.json` 🤗 

for the readme any doc generator can then choose if to show protected properties or not

**Comment by bennypowers** [comment]
That works for me

**Comment by lufego** [comment]
@daKmoR apparently `@private` tag is not working as it should. I've opened https://github.com/runem/web-component-analyzer/issues/106

**Comment by runem** [comment]
I have now implemented support for @private and @protected jsdoc annotations on the [visibility](https://github.com/runem/web-component-analyzer/tree/visibility) branch. The analyzer defaults to only emitting `public` properties, but it's possible to give minimum visibility to the config, when running the analyzer, in order to emit `protected` or `private` properties as well :-) 

I'll close this issue when the feature has been published :tada:

**Comment by runem** [comment]
Version `1.0.0` is live with support for `@private` and `@protected` :tada:
