### ISSUE TITLE
`@private` tag doesn't work as expected

### ISSUE THREAD

**Issue by lufego** [runem/web-component-analyzer#106]
## Current behavior
If I initialize a prop like:

```js
/**
   * This should be hidden from generated documentation
   * @private
   */
  @property({ attribute: false }) loading;
```

It will still be added to the table markdown.

## Expected result:
Since it's a `@private` it should be hidden from documentation

**Comment by runem** [comment]
Version `1.0.0` is live with support for `@private` and `@protected` :tada:
