### ISSUE TITLE
Custom interfaces for ts/tsx

### ISSUE THREAD

**Issue by alazurenko** [runem/web-component-analyzer#116]
Hello, 
Thank you for your effort on building this useful tool 👍 

I have a question regarding  name of the interface that is used during the analyze of ts files: 
Would be feasible to customize the name of an interface for analysis. For instance, `HTMLElementTagNameMap` to `IntrinsicElements`? 

What do you think?

**Comment by runem** [comment]
Thanks, I'm happy you like it ☀️

Definitely! I might built a separate JSX-flavor for this, that can be activated via a flag (eg. --jsx). Would there be more JSX-declaration specific syntax to support? Eg. `IntrinsicAttributes`?

**Comment by alazurenko** [comment]
Thanks for the reply! 
I believe it would be beneficial to have them :)

**Comment by runem** [comment]
Version `1.0.0`, which has just been published, supports `IntrinsicElements` and `IntrinsicAttributes` out of the box :tada:
