### ISSUE TITLE
Analyze seems to pick up variables inside my LitElement code (in ternary operators)

### ISSUE THREAD

**Issue by hsablonniere** [runem/web-component-analyzer#123]
Hey, I'm not sure what I'm doing wrong but I tried to reduce the test case:

```js
import { html, LitElement } from 'lit-element';

export class TestComponent extends LitElement {
  render () {
    const someBoolean = (42 > 2);
    return html`<div>${someBoolean ? 'yes' : 'no'}</div>`;
  }
}

window.customElements.define('test-component', TestComponent);
```

When I run `wca`, the JSON output picks up the internal variable `someBoolean`.

```json
{
  "version": 2,
  "tags": [
    {
      "name": "test-component",
      "properties": [
        {
          "name": "someBoolean",
          "type": "\"yes\" | \"no\""
        }
      ]
    }
  ]
}
```

1. Why is this doing this?
2. Is this a bug?
3. Can I help? ;-)

**Comment by hsablonniere** [comment]
NOTES:

* It does not matter if the code I showed is in the `render` method. If I rename it to `foobar` I still have this problem.
* If I don't use the `someBoolean` with a ternary operator, I don't get the issue.

**Comment by runem** [comment]
Funky issue! Thanks for reporting :+1: 

Should be fixed now, but not published yet!

**Comment by hsablonniere** [comment]
Great ;-)
