### ISSUE TITLE
Multiline @fires event description is not emitted in the output

### ISSUE THREAD

**Issue by ashubham** [runem/web-component-analyzer#129]
```js
/**
* @fires load - This is the first line.
* This is the second line.
*/
```
Does not work, the description output for both json/markdown is empty for the event.
```json
"events": [
        {
          "name": "load"
        }
      ]
```

This works however:
```js
/**
* @fires load - This is the first line. This is the second line.
*/
```

**Comment by runem** [comment]
Hi Ashish, thanks for using WCA and thanks for reporting this issue :-)

This bug is fixed in the next version that is being released in a couple of days. You can verify it by trying the beta version `1.0.0-next.16`. I will close this issue when it has been released.

**Comment by ashubham** [comment]
Thanks!
