### ISSUE TITLE
[LitElement] Default array values not extracted

### ISSUE THREAD

**Issue by kylewelsby** [runem/web-component-analyzer#130]
Components that are written with array input do not out-put the programmed default values in the properties table. 

### Example code

```
class MyComp extends LitElement {
  /**
   * should render default values
   */
  @property({
    type: Array
  })
  myArray = ["value"]
}
```

### Expected output

| Property | Attribute | Type | Default | Description |
|----------|----------|------|--------|-------------|
| `myArray` | `myArray` | `string[]` | ["value"] | should render default values |

**Comment by runem** [comment]
Thanks for reporting this issue! It has now been fixed on the `refactor` branch. I will close this issue when the fix has been published :+1:
