### ISSUE TITLE
Methods not included in output

### ISSUE THREAD

**Issue by justinfagnani** [runem/web-component-analyzer#133]
The docs seem to indicate that methods should be included in the output, but I don't see them. 

[Playground Example](https://runem.github.io/web-component-analyzer/?code=import%20%7B%20customElement%2C%20LitElement%2C%20property%20%7D%20from%20%22lit-element%22%3B%0A%0A%2F**%0A%20*%20A%20text%20field%20web%20component%0A%20*%2F%0A%40customElement(%22text-field%22)%0Aexport%20class%20TextField%20extends%20LitElement%20%7B%0A%20%20%2F**%0A%20%20%20*%20The%20value%20of%20the%20text%20field%0A%20%20%20*%20%40attr%0A%20%20%20*%2F%0A%20%20value%20%3D%20%22default%20value%22%3B%0A%20%20%0A%20%20%40property(%7B%20attribute%3A%20%22max-length%22%20%7D)%20maxLength%20%3D%20100%3B%0A%20%20%0A%20%20%40property(%7B%20attribute%3A%20false%20%7D)%20errorObject%20%3D%20%7Bdescription%3A%20%22error%22%7D%3B%0A%20%20%0A%20%20%2F**%0A%20%20%20*%20Disables%20this%20element%0A%20%20%20*%2F%0A%20%20%40property(%7B%20type%3A%20Boolean%20%7D)%20disabled%20%3D%20false%3B%0A%20%20%0A%20%20%2F**%20%40public%20A%20method%20**%2F%0A%20%20aMethod()%3A%20number%20%7B%0A%20%20%20%20return%2015%3B%0A%20%20%7D%0A%7D%0A)

**Comment by runem** [comment]
Thanks for the heads up! Forgot to deploy the new version of WCA to gh-pages, - it should work now :sunny:  Be aware that methods are only included in the markdown format for now :-)
