### ISSUE TITLE
Support original jsdoc event implementation

### ISSUE THREAD

**Issue by NickdeK** [runem/web-component-analyzer#139]
The official [jsdoc implementation](https://jsdoc.app/tags-fires.html) requires the event to be defined with class and event type. Using the method described in the readme gives me a warning in IntelliJ editors: `Unresolved variable or type 'event:input-switch-check-changed'`

So instead of :
`/* @fires input-switch-check-changed Fires when check property changes */` 
I need to write the following doc to get rid of the warning: 
`/* @fires InputSwitch#[CustomEvent]input-switch-check-changed Fires when check property changes */`

I can understand you still want to support the original example because it's less verbose, but is it possible to also support the original jsdoc event definition?

**Comment by runem** [comment]
The notation is now supported in version `1.0.3` of WCA, thanks for catching this bug :tada:
