### ISSUE TITLE
Boolean attr with default value

### ISSUE THREAD

**Issue by bennypowers** [runem/web-component-analyzer#147]
## Input
```js
/**
 * If true, when updates are found, the page will automatically
 * reload, so long as the user has not yet interacted with it.
 * @attr {boolean} [auto-reload=false]
 */
get autoReload() {
  return this.hasAttribute('auto-reload');
}
```

## Expected

| Property        | Attribute       | Type            | Default | Description                                      |
|-----------------|-----------------|-----------------|---------|--------------------------------------------------|
| `autoReload`    | `auto-reload`   | `boolean`       | false   | If true, when updates are found, the page will automatically<br />reload, so long as the user has not yet interacted with it. |

## Actual

| Property        | Attribute       | Type            | Default | Description                                      |
|-----------------|-----------------|-----------------|---------|--------------------------------------------------|
| `autoReload`    | `auto-reload`   | `boolean`       |         | If true, when updates are found, the page will automatically<br />reload, so long as the user has not yet interacted with it. |

If I apply `@default false`, I get

| Property        | Attribute       | Type            | Default | Description                                      |
|-----------------|-----------------|-----------------|---------|--------------------------------------------------|
| `autoReload`    | `auto-reload`   | `boolean`       | "false"  | If true, when updates are found, the page will automatically<br />reload, so long as the user has not yet interacted with it. |

**Comment by bennypowers** [comment]
`@workaround {AwfulHack}`: I can put this at the very end of my constructor

```js
if (this.hasAttribute('auto-reload')) return;

this.autoReload = false;
```

**Comment by runem** [comment]
Hey, thanks for opening this issue :-)

I forgot to apply default values when parsing/applying jsdoc for members of a component. It has been fixed now, and will be included in the next release.
