### ISSUE TITLE
Need to define custom element for analyzer to work

### ISSUE THREAD

**Issue by leifriksheim** [runem/web-component-analyzer#163]
I have an issue where I don't want to define the element to the registry in the main web component file. I have individual files, and I do all the registration in one main.js file like this.

```js
import { Button } from "./components/button";
import { Checkbox } from "./components/checkbox";

customElements.define("core-button", Button);
customElements.define("core-checkbox", Checkbox);
``` 

It seems like the analyzer needs the registration to happen within the same file as the component is written. Is this the case?

**Comment by PaulHMason** [comment]
I'd also like to be able to generate documentation for mixins.

**Comment by runem** [comment]
Thanks for opening this issue! 

I can't seem to reproduce this problem with the newest version of `WCA`, so I consider this issue fixed. Please reopen this issue if you can still reproduce it and I'll look further into the matter :-)
