### ISSUE TITLE
When making your custom flavors, you cannot beneficiate from others

### ISSUE THREAD

**Issue by fdesforges** [runem/web-component-analyzer#170]
First, thanks for this project.

I have made a custom flavor for handling my Web components library, and i'm using it with the node API : 

```
const result = analyzeSourceFile(file, { 
  program,
  flavors: [new ComponentFlavor()],
  verbose: true
})
```
So far so good, but I don't get the support for JSDOC  properties since I cannot import the jsdoc utils : 
`{ getJsDoc, getJsDocType } from "../../util/js-doc-util";`

And I cannot get the support of the JSDoc flavor for adding events (@fire).

Exporting the default flavor constant, or each individivual flavors like the commented one here, may be an easy solution (plus the jsdoc helper) :
https://github.com/runem/web-component-analyzer/blob/f93d25203438f63257cf6da31709bc25c7e1c5df/src/analyze/index.ts

But i understandard that if you comment them, it's on purpose.

If you want I can propose a pull request, where i will uncomment the jsdoc flavor ?

**Comment by fire** [comment]
Hi. I am fire.
