### ISSUE TITLE
Support Mixins

### ISSUE THREAD

**Issue by runem** [runem/web-component-analyzer#33]
Right now `web-component-analyzer` doesn't support mixins. This issue will track the implementation of that feature. 

### Example 1:

```javascript
const SomeMixin = (Base) => {
   return class Mixin extends Base {
        static get observedAttributes() { 
            return ["c", "d"]; 
        }
    }
}

class SomeElement extends SomeMixin(HTMLElement) {
    static get observedAttributes() { 
        return ["a", "b", ...super.observedAttributes]; 
    }
}
```

Analyzing the above should find "a"/"b" attributes (which it does right now) and it should find "c"/"d" attributes (which it doesn't do right now). 

### Example 2: 

```typescript
type Constructor<T = {}> = new (...args: any[]) => T;
const SomeMixin = <C extends Constructor<HTMLElement>>(Base: C) => {
    class Mixin extends Base {
        @property({ type: String }) mixinProperty: string;
    }
    return Mixin;
}

@customElement("some-element")
class SomeElement extends SomeMixin(LitElement) {
    @property({ type: String }) elementProperty: string;
}
```

Analyzing the above should find "elementProperty" (which it does right now) and it should find "mixinProperty" (which it doesn't do right now). 

### Limitations
* Right now it doesn't analyze the absent of "super" calls, so everything returned in the inheritance chain will be included. However this limitation is in another part of the analyzer, so it should be fixed in a seperate issue.
* I will also implement support for mixin jsdoc tags, but that should be done in another issue as well.

**Comment by daKmoR** [comment]
### Example 3:
```js
export const FieldCustomMixin = dedupeMixin(
  superclass =>
    class FieldCustomMixin extends superclass {
        static get observedAttributes() { 
            return ["c", "d"]; 
        }
    },
);

class SomeElement extends SomeMixin(HTMLElement) {
    static get observedAttributes() { 
        return ["a", "b", ...super.observedAttributes]; 
    }
}
```

using a mixin function that dedupes applied mixins... you can see an implementation [here](https://github.com/ing-bank/lion/blob/master/packages/core/src/dedupeMixin.js).

Result should be the same as in Example 1.

not sure if that is easily possible - might need a special JsDoc annotation? what do you think?

**Comment by runem** [comment]
I think this should definitely be possible. 

Regarding parsing, I think the best approach would be to search the AST of the mixin identifier, for the first occurrence of a Class Declaration, in order to find the mixin class. 

Regarding deduping, the analyzer already dedupes everything it analyzes, so this shouldn't be a problem. 

In addition, I will use [Lion Web Components](https://github.com/ing-bank/lion) to setup up some snapshot tests in this repository. The library has a lot of components using mixins, so as a start `lit-analyzer` should be able to analyze them :-)
