### ISSUE TITLE
Errors during `npm test`

### ISSUE THREAD

**Issue by mwcz** [runem/web-component-analyzer#4]
I was going to take a stab at adding a CLI test, but I ran into issues running the existing test suite.  Error log below.  Is there anything other than `npm install; npm test` that I need to run to set up the test suite?

<details>
  <summary>error log</summary>
  <pre><code>
> web-component-analyzer@0.1.4 test /home/user/projects/wca
> ava

  ✔ components › custom-element-test.ts › Custom Element: Attributes

  Uncaught exception in test/snapshots/stencil-progress-ring.ts

  /home/user/projects/wca/test/helpers/source-file-test.ts:30

   29:     console.log(_compiledResult.program.getSourceFiles().map(sf => sf.fi…
   30:     throw new Error(`Couldn't find source file match: ${fileName}`);     
   31:   } else if (sourceFiles.length > 1) {                                   

  Error: Couldn't find source file match: /progress-ring-component/dist/types/components.d.ts

  getSourceFile (test/helpers/source-file-test.ts:30:9)
  testResult (test/helpers/source-file-test.ts:40:8)
  Object.testResultSnapshot (test/helpers/source-file-test.ts:49:2)
  Object.<anonymous> (test/snapshots/stencil-progress-ring.ts:4:1)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

  Uncaught exception in test/snapshots/polymer-app-layout.ts

  /home/user/projects/wca/test/helpers/source-file-test.ts:30

   29:     console.log(_compiledResult.program.getSourceFiles().map(sf => sf.fi…
   30:     throw new Error(`Couldn't find source file match: ${fileName}`);     
   31:   } else if (sourceFiles.length > 1) {                                   

  Error: Couldn't find source file match: @polymer/app-layout/app-drawer/app-drawer.d.ts

  getSourceFile (test/helpers/source-file-test.ts:30:9)
  testResult (test/helpers/source-file-test.ts:40:8)
  Object.testResultSnapshot (test/helpers/source-file-test.ts:49:2)
  Object.<anonymous> (test/snapshots/polymer-app-layout.ts:4:1)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

  Uncaught exception in test/snapshots/lit-element-mwc.ts

  /home/user/projects/wca/test/helpers/source-file-test.ts:30

   29:     console.log(_compiledResult.program.getSourceFiles().map(sf => sf.fi…
   30:     throw new Error(`Couldn't find source file match: ${fileName}`);     
   31:   } else if (sourceFiles.length > 1) {                                   

  Error: Couldn't find source file match: @material/mwc-button/mwc-button.d.ts

  getSourceFile (test/helpers/source-file-test.ts:30:9)
  testResult (test/helpers/source-file-test.ts:40:8)
  Object.testResultSnapshot (test/helpers/source-file-test.ts:49:2)
  Object.<anonymous> (test/snapshots/lit-element-mwc.ts:4:1)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

  Uncaught exception in test/snapshots/stencil-ionic.ts

  /home/user/projects/wca/test/helpers/source-file-test.ts:30

   29:     console.log(_compiledResult.program.getSourceFiles().map(sf => sf.fi…
   30:     throw new Error(`Couldn't find source file match: ${fileName}`);     
   31:   } else if (sourceFiles.length > 1) {                                   

  Error: Couldn't find source file match: @material/mwc-button/mwc-button.d.ts

  getSourceFile (test/helpers/source-file-test.ts:30:9)
  testResult (test/helpers/source-file-test.ts:40:8)
  Object.testResultSnapshot (test/helpers/source-file-test.ts:49:2)
  Object.<anonymous> (test/snapshots/stencil-ionic.ts:4:1)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

  Uncaught exception in test/snapshots/polymer-paper-button.ts

  /home/user/projects/wca/test/helpers/source-file-test.ts:30

   29:     console.log(_compiledResult.program.getSourceFiles().map(sf => sf.fi…
   30:     throw new Error(`Couldn't find source file match: ${fileName}`);     
   31:   } else if (sourceFiles.length > 1) {                                   

  Error: Couldn't find source file match: @polymer/paper-button/paper-button.d.ts

  getSourceFile (test/helpers/source-file-test.ts:30:9)
  testResult (test/helpers/source-file-test.ts:40:8)
  Object.testResultSnapshot (test/helpers/source-file-test.ts:49:2)
  Object.<anonymous> (test/snapshots/polymer-paper-button.ts:4:1)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

  Uncaught exception in test/snapshots/vanilla-masonry-layout.ts

  /home/user/projects/wca/test/helpers/source-file-test.ts:30

   29:     console.log(_compiledResult.program.getSourceFiles().map(sf => sf.fi…
   30:     throw new Error(`Couldn't find source file match: ${fileName}`);     
   31:   } else if (sourceFiles.length > 1) {                                   

  Error: Couldn't find source file match: @appnest/masonry-layout/masonry-layout.d.ts

  getSourceFile (test/helpers/source-file-test.ts:30:9)
  testResult (test/helpers/source-file-test.ts:40:8)
  Object.testResultSnapshot (test/helpers/source-file-test.ts:49:2)
  Object.<anonymous> (test/snapshots/vanilla-masonry-layout.ts:4:1)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

  ✖ test/snapshots/stencil-progress-ring.ts exited with a non-zero exit code: 1
  ✖ test/snapshots/vanilla-masonry-layout.ts exited with a non-zero exit code: 1
  ✖ test/snapshots/polymer-app-layout.ts exited with a non-zero exit code: 1
  ✖ test/snapshots/polymer-paper-button.ts exited with a non-zero exit code: 1
  ✖ test/snapshots/lit-element-mwc.ts exited with a non-zero exit code: 1
  ✖ test/snapshots/stencil-ionic.ts exited with a non-zero exit code: 1

  1 test passed
  6 uncaught exceptions

</code></pre>
</details>

**Comment by mwcz** [comment]
Ahh, I noticed that `dev/` has a package.json in it, so I ran npm install there as well, and now npm test works.  It would be nice to either document that step or automate it.

Would you consider either:

		"pretest": "cd dev && npm install"

Or adding a note in the README with the steps for running tests?  I'm happy to send a PR for either approach.

**Comment by runem** [comment]
Thank you so much for taking your time to add a CLI test! I'm very open for introducing CLI tests 😊 

The reason I made an entire folder with it's own `package.json` is to to run snapshot testing on popular web component libraries.

I think the adding a `pretest` script would make sense, so feel free to add it 👍
