### ISSUE TITLE
Interfaces that extend imported interfaces don't get extended fields

### ISSUE THREAD

**Issue by rictic** [runem/web-component-analyzer#59]
Consider a project like:

```typescript
// base.ts
export interface Checked {
  checked: boolean;
}
```

```typescript
// main.ts
import {Checked} from './base';

interface CheckableElement extends HTMLElement, Checked {}

declare global {
  interface HTMLElementTagNameMap {
    'checkable-element': CheckableElement;
  }
}
```

web-component-analyzer appears not to know that `<checkable-element`> has a `.checked` property. The issue seems to be specific to interfaces that extend imported interfaces. Specifically, I checked these cases:

* ✅class extending another class declared in the same file
* ✅class extending another class imported from another file
* ✅interface extending an interface declared in the same file 
* ❌interface extending an interface imported from another file

Standalone repro at https://github.com/rictic/repro-wca-import-interface-issue

**Comment by runem** [comment]
Thank you so much for this issue and the repro. I have now fixed the problem and added test cases to [this file](https://github.com/runem/web-component-analyzer/blob/master/test/flavors/custom-element/extending-test.ts) so it wont happen again :tada:

**Comment by rictic** [comment]
Nice! I can confirm that that fixes the bug here.

I think there's something still up with the original code that I reduced this down from, which is that the plugin can't find the `checked` property on `<paper-checkbox>`. I'm working on a regression now.
