### ISSUE TITLE
Add more info to description fields in the vscode output

### ISSUE THREAD

**Issue by runem** [runem/web-component-analyzer#6]
We can include information currently not present in the `vscode` format by adding it to the `description` fields.

`attributes` and `tags` in the `vscode` output format have `description` fields that will show when the user hovers above them in the IDE.

### Tags
Here we can include **events**, **slots**, **attributes**, **properties**, **css vars** like the following:

```json
{
   "name": "my-tag",
   "description": "Here is the description\n\nEvents:\n * changed: Event description\n\nSlots:\n * right\n *left"
}
```

### Attributes
Here we can include **type**, **associated property**, **default value**.

```json
{
   "name": "text",
   "description": "Here is the description\n\nType: string\nProperty: text\nDefault: 'default value'"
}
```

I will also have to look into if the vscode format supports using markdown in the description fields :-)

**Comment by runem** [comment]
With commit https://github.com/runem/web-component-analyzer/commit/9a728a8e15ee8d4f8668e9ed9277ae748289ce7c the vscode format now outputs a lot of extra information. Unfortunately the format doesn't support markdown as of now, so this was the best I could do:

<img width="544" alt="Screenshot 2019-06-05 at 17 35 10" src="https://user-images.githubusercontent.com/5372940/58970033-e8bddd00-87b8-11e9-87df-b4f3ee629e42.png">

<img width="830" alt="Screenshot 2019-06-05 at 17 34 51" src="https://user-images.githubusercontent.com/5372940/58970170-2b7fb500-87b9-11e9-8fa5-406f2dbdf2f5.png">

**Comment by mwcz** [comment]
Very nice!
